/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Admin;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import controller.Admin.LoginController;

import java.awt.Font;
import javax.swing.JButton;
import java.awt.Color;
import java.awt.EventQueue;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.ActionEvent;
import javax.swing.JLabel;

/**
 *
 * @author oXCToo
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public LoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        emailField = new javax.swing.JTextField();
        emailField.setBounds(64, 148, 278, 22);
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setBounds(62, 51, 85, 34);
        emailLabel = new javax.swing.JLabel();
        emailLabel.setBounds(64, 128, 23, 14);
        passwordLabel = new javax.swing.JLabel();
        passwordLabel.setBounds(64, 207, 41, 14);
        passwordField = new javax.swing.JPasswordField();
        passwordField.setBounds(64, 239, 278, 22);
        kGradientPanel2 = new keeptoo.KGradientPanel();
        kGradientPanel2.setBounds(62, 316, 278, 44);
        continueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 204, 204));
        kGradientPanel1.setkGradientFocus(600);
        kGradientPanel1.setkEndColor(new java.awt.Color(153, 0, 153));
        kGradientPanel1.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        emailField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailField.setForeground(new java.awt.Color(102, 102, 102));
        emailField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));

        jLabel3.setFont(new Font("Segoe UI", Font.BOLD, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("<html>Login\n</html>");

        emailLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(153, 153, 153));
        emailLabel.setText("email");

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(153, 153, 153));
        passwordLabel.setText("password");

        passwordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordField.setForeground(new java.awt.Color(102, 102, 102));
        passwordField.setText("jPasswordField1");
        passwordField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));

        kGradientPanel2.setkEndColor(new java.awt.Color(12, 91, 160));
        kGradientPanel2.setkGradientFocus(200);
        kGradientPanel2.setkEndColor(new java.awt.Color(153, 0, 153));
        kGradientPanel2.setLayout(null);

        continueLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        continueLabel.setForeground(new java.awt.Color(255, 255, 255));
        continueLabel.setText("CONTINUE");
        kGradientPanel2.add(continueLabel);
        continueLabel.setBounds(102, 11, 71, 20);

        kGradientPanel1.add(jPanel1);
        jPanel1.setBounds(698, 128, 400, 416);
        jPanel1.setLayout(null);
        jPanel1.add(jLabel3);
        jPanel1.add(passwordLabel);
        jPanel1.add(emailLabel);
        jPanel1.add(emailField);
        jPanel1.add(passwordField);
        jPanel1.add(kGradientPanel2);
        
        loginButton = new JButton();
        loginButton.setBounds(0, 0, 278, 44);
        loginButton.setContentAreaFilled(false); // Làm cho nền của nút trong suốt
        loginButton.setBorderPainted(false); // Loại bỏ đường viền của nút
        loginButton.setOpaque(false); // Loại bỏ tính năng vẽ màu nền của nút
        kGradientPanel2.add(loginButton);
        loginButton.setBackground(buttonBackgroundColor); // Đặt màu nền cho nút

        errorLabel = new JLabel("");
        errorLabel.setBounds(62, 291, 280, 14);
        jPanel1.add(errorLabel);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html>Simplify Student Management with Ease and Efficiency \r\n");
        kGradientPanel1.add(jLabel1);
        jLabel1.setBounds(191, 247, 343, 50);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("*#####*");
        kGradientPanel1.add(jLabel2);
        jLabel2.setBounds(191, 145, 52, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 153, 255));
        jLabel4.setText("STUDENT MANAGEMENT SYSTEM");
        kGradientPanel1.add(jLabel4);
        jLabel4.setBounds(191, 195, 324, 25);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assert/admin/grap.png"))); // NOI18N
        kGradientPanel1.add(jLabel9);
        jLabel9.setBounds(198, 347, 400, 260);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Legendary");
        kGradientPanel1.add(jLabel11);
        jLabel11.setBounds(191, 106, 161, 32);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(kGradientPanel1, GroupLayout.DEFAULT_SIZE, 1360, Short.MAX_VALUE)
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(kGradientPanel1, GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
        );
        getContentPane().setLayout(layout);

        pack();
        clearPasswordField();

        // Add focus listeners to clear error status when the user starts typing
        emailField.addFocusListener(new FocusAdapter() {
            public void focusGained(FocusEvent e) {
                clearError();
            }
        });

        passwordField.addFocusListener(new FocusAdapter() {
            public void focusGained(FocusEvent e) {
                clearError();
            }
        });


        
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    LoginView frame = new LoginView();
                    LoginController controller = new LoginController(frame); // Pass the view to the controller
                    frame.setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }
    public void addLoginListener(ActionListener listener) {
    	loginButton.addActionListener(listener);
    }

    public String getEmail() {
        return emailField.getText();
    }

    public String getPassword() {
        return new String(passwordField.getPassword());
    }

    public void displayEmailError(String message) {
        errorLabel.setText(message);
        emailField.setBackground(Color.PINK);
        errorLabel.setForeground(Color.RED);

    }

    public void displayPasswordError(String message) {
        errorLabel.setText(message);
        passwordField.setBackground(Color.PINK);
        errorLabel.setForeground(Color.RED);

    }
    public void displayErrorMessage(String message) {
        errorLabel.setText(message);

        // Highlight email and password fields in red
        emailField.setBackground(Color.PINK);
        passwordField.setBackground(Color.PINK);
        errorLabel.setForeground(Color.RED);
    }
    private void clearPasswordField() {
        passwordField.setText("");
    }

    public void clearError() {
        errorLabel.setText("");
        emailField.setBackground(Color.WHITE);
        passwordField.setBackground(Color.WHITE);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel continueLabel;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField emailField;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private JLabel errorLabel;
    private JButton loginButton;
    private Color buttonBackgroundColor = new Color(255, 0, 255);
}